apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misra-platform.fullname" . }}-clang-worker
  labels:
    {{- include "misra-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.clangWorker }}
  selector:
    matchLabels:
      app: misra-clang-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: misra-clang-worker
        {{- include "misra-platform.labels" . | nindent 8 }}
    spec:
      containers:
        - name: clang-worker
          image: "{{ .Values.image.clangWorker.repository }}:{{ .Values.image.clangWorker.tag }}"
          imagePullPolicy: {{ .Values.image.clangWorker.pullPolicy }}
          ports:
            - containerPort: 50051
              name: grpc
          readinessProbe:
            exec:
              command: ["/app/healthcheck.sh"]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources.clangWorker | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "misra-platform.fullname" . }}-clang-worker
spec:
  selector:
    app: misra-clang-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
