apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misra-platform.fullname" . }}-frontend
  labels:
    {{- include "misra-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: misra-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: misra-frontend
        {{- include "misra-platform.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "misra-platform.fullname" . }}-frontend
spec:
  selector:
    app: misra-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
      name: http
